In [1]:
from numpy import *
num_movies = 10
num_users = 5
ratings = random.randint(11, size = (num_movies, num_users))
print(ratings)

[[10  0  1  2  4]
 [ 6  8  4  6  3]
 [ 2  4  7  1  3]
 [ 0  7  6  1  0]
 [ 7  8  6  0  8]
 [ 0  7  4  6  1]
 [10  0  9  3  8]
 [ 2 10  2  6  6]
 [ 0  0  6  8  0]
 [ 0  8  5  9  3]]


In [2]:
did_rate = (ratings != 0) * 1

In [3]:
ratings.shape

(10, 5)

In [4]:
nikhil_ratings=zeros((num_movies, 1))

In [5]:
nikhil_ratings[0] = 8
nikhil_ratings[4] = 7
nikhil_ratings[7] = 3


In [6]:
print(nikhil_ratings)

[[8.]
 [0.]
 [0.]
 [0.]
 [7.]
 [0.]
 [0.]
 [3.]
 [0.]
 [0.]]


In [7]:
ratings = append(nikhil_ratings,ratings,axis=1)
did_rate = append((nikhil_ratings != 0) * 1,did_rate,axis=1)

In [8]:
ratings

array([[ 8., 10.,  0.,  1.,  2.,  4.],
       [ 0.,  6.,  8.,  4.,  6.,  3.],
       [ 0.,  2.,  4.,  7.,  1.,  3.],
       [ 0.,  0.,  7.,  6.,  1.,  0.],
       [ 7.,  7.,  8.,  6.,  0.,  8.],
       [ 0.,  0.,  7.,  4.,  6.,  1.],
       [ 0., 10.,  0.,  9.,  3.,  8.],
       [ 3.,  2., 10.,  2.,  6.,  6.],
       [ 0.,  0.,  0.,  6.,  8.,  0.],
       [ 0.,  0.,  8.,  5.,  9.,  3.]])

In [9]:
did_rate

array([[1, 1, 0, 1, 1, 1],
       [0, 1, 1, 1, 1, 1],
       [0, 1, 1, 1, 1, 1],
       [0, 0, 1, 1, 1, 0],
       [1, 1, 1, 1, 0, 1],
       [0, 0, 1, 1, 1, 1],
       [0, 1, 0, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [0, 0, 0, 1, 1, 0],
       [0, 0, 1, 1, 1, 1]])

In [10]:
def normalize_ratings(ratings,did_rate):
    num_movies = ratings.shape[0]
    
    ratings_mean = zeros(shape=(num_movies,1))
    ratings_norm = zeros(shape = ratings.shape)
    for i in range(num_movies):
        #get all indexes where there is 1
        idx = where(did_rate[i] ==1)[0]
        
        ratings_mean[i] = mean(ratings[i, idx])
        ratings_norm[i, idx] = ratings[i, idx] - ratings_mean[i]
    return ratings_norm,ratings_mean

    

In [11]:
ratings, ratings_mean = normalize_ratings(ratings, did_rate)


In [12]:
ratings

array([[ 3.        ,  5.        ,  0.        , -4.        , -3.        ,
        -1.        ],
       [ 0.        ,  0.6       ,  2.6       , -1.4       ,  0.6       ,
        -2.4       ],
       [ 0.        , -1.4       ,  0.6       ,  3.6       , -2.4       ,
        -0.4       ],
       [ 0.        ,  0.        ,  2.33333333,  1.33333333, -3.66666667,
         0.        ],
       [-0.2       , -0.2       ,  0.8       , -1.2       ,  0.        ,
         0.8       ],
       [ 0.        ,  0.        ,  2.5       , -0.5       ,  1.5       ,
        -3.5       ],
       [ 0.        ,  2.5       ,  0.        ,  1.5       , -4.5       ,
         0.5       ],
       [-1.83333333, -2.83333333,  5.16666667, -2.83333333,  1.16666667,
         1.16666667],
       [ 0.        ,  0.        ,  0.        , -1.        ,  1.        ,
         0.        ],
       [ 0.        ,  0.        ,  1.75      , -1.25      ,  2.75      ,
        -3.25      ]])

In [13]:
ratings_mean

array([[5.        ],
       [5.4       ],
       [3.4       ],
       [4.66666667],
       [7.2       ],
       [4.5       ],
       [7.5       ],
       [4.83333333],
       [7.        ],
       [6.25      ]])

In [14]:
#update some of the key values now
num_users = ratings.shape[1]
num_features = 3
#Initialize Parameters theta(user_prefs), X(movie_features)
movie_features = random.randn(num_movies,num_features)
user_prefs = random.randn(num_users,num_features)
initial_X_and_theta = r_[movie_features.T.flatten(),user_prefs.T.flatten()]

In [15]:
movie_features

array([[ 0.07695652, -1.88127091, -1.98345064],
       [ 0.43106361,  0.38778814,  0.71145247],
       [-1.31748871, -0.13547442, -1.31412936],
       [ 0.0365604 ,  0.28729856, -1.44929619],
       [ 0.03785185, -2.1089614 , -0.55556544],
       [-0.16061025, -0.03980504,  0.36273944],
       [-1.83606881, -0.7138777 ,  1.52494555],
       [ 0.26261092,  0.92265322, -1.47897496],
       [-0.63489693,  0.62066302,  0.52109651],
       [ 0.52705976, -1.10773788,  1.90342017]])

In [16]:
user_prefs

array([[-0.66936764, -0.88395782,  0.61141144],
       [-0.31282544,  0.89906122,  0.67755035],
       [ 0.38128959, -1.16864119,  0.68359495],
       [ 1.16520452,  1.0202663 , -0.59465236],
       [ 0.25997244,  0.90734525,  0.47029973],
       [ 0.20210925,  1.42249341, -2.42661917]])

In [17]:
initial_X_and_theta.shape

(48,)

In [18]:
movie_features.T.flatten()

array([ 0.07695652,  0.43106361, -1.31748871,  0.0365604 ,  0.03785185,
       -0.16061025, -1.83606881,  0.26261092, -0.63489693,  0.52705976,
       -1.88127091,  0.38778814, -0.13547442,  0.28729856, -2.1089614 ,
       -0.03980504, -0.7138777 ,  0.92265322,  0.62066302, -1.10773788,
       -1.98345064,  0.71145247, -1.31412936, -1.44929619, -0.55556544,
        0.36273944,  1.52494555, -1.47897496,  0.52109651,  1.90342017])

In [19]:
def unroll_params(X_and_theta, num_users, num_movies, num_features):
	# Retrieve the X and theta matrixes from X_and_theta, based on their dimensions (num_features, num_movies, num_movies)
	# --------------------------------------------------------------------------------------------------------------
	# Get the first 30 (10 * 3) rows in the 48 X 1 column vector
	first_30 = X_and_theta[:num_movies * num_features]
	# Reshape this column vector into a 10 X 3 matrix
	X = first_30.reshape((num_features, num_movies)).transpose()
	# Get the rest of the 18 the numbers, after the first 30
	last_18 = X_and_theta[num_movies * num_features:]
	# Reshape this column vector into a 6 X 3 matrix
	theta = last_18.reshape(num_features, num_users ).transpose()
	return X, theta

In [20]:
temp = initial_X_and_theta
first_30 = temp[:num_movies * num_features]

In [21]:
first_30

array([ 0.07695652,  0.43106361, -1.31748871,  0.0365604 ,  0.03785185,
       -0.16061025, -1.83606881,  0.26261092, -0.63489693,  0.52705976,
       -1.88127091,  0.38778814, -0.13547442,  0.28729856, -2.1089614 ,
       -0.03980504, -0.7138777 ,  0.92265322,  0.62066302, -1.10773788,
       -1.98345064,  0.71145247, -1.31412936, -1.44929619, -0.55556544,
        0.36273944,  1.52494555, -1.47897496,  0.52109651,  1.90342017])

In [22]:
first_30.reshape((num_features, num_movies)).transpose()

array([[ 0.07695652, -1.88127091, -1.98345064],
       [ 0.43106361,  0.38778814,  0.71145247],
       [-1.31748871, -0.13547442, -1.31412936],
       [ 0.0365604 ,  0.28729856, -1.44929619],
       [ 0.03785185, -2.1089614 , -0.55556544],
       [-0.16061025, -0.03980504,  0.36273944],
       [-1.83606881, -0.7138777 ,  1.52494555],
       [ 0.26261092,  0.92265322, -1.47897496],
       [-0.63489693,  0.62066302,  0.52109651],
       [ 0.52705976, -1.10773788,  1.90342017]])

In [23]:
num_features

3