In [1]:
from numpy import *
num_movies = 10
num_users = 5
ratings = random.randint(11, size = (num_movies, num_users))
print(ratings)

[[ 5  7  7  0  8]
 [ 9  6  5  6  8]
 [ 5  6  8  8  0]
 [ 9  1  9  1  8]
 [ 4  0  8  4  0]
 [ 5  8  6  9  2]
 [ 7  3  9  7  5]
 [10  3  9  3  5]
 [ 2  5  9  7  2]
 [ 1  2  3  9  2]]


In [2]:
did_rate = (ratings != 0) * 1

In [3]:
ratings.shape

(10, 5)

In [4]:
nikhil_ratings=zeros((num_movies, 1))

In [5]:
nikhil_ratings[0] = 8
nikhil_ratings[4] = 7
nikhil_ratings[7] = 3


In [6]:
print(nikhil_ratings)

[[8.]
 [0.]
 [0.]
 [0.]
 [7.]
 [0.]
 [0.]
 [3.]
 [0.]
 [0.]]


In [7]:
ratings = append(nikhil_ratings,ratings,axis=1)
did_rate = append((nikhil_ratings != 0) * 1,did_rate,axis=1)

In [8]:
ratings

array([[ 8.,  5.,  7.,  7.,  0.,  8.],
       [ 0.,  9.,  6.,  5.,  6.,  8.],
       [ 0.,  5.,  6.,  8.,  8.,  0.],
       [ 0.,  9.,  1.,  9.,  1.,  8.],
       [ 7.,  4.,  0.,  8.,  4.,  0.],
       [ 0.,  5.,  8.,  6.,  9.,  2.],
       [ 0.,  7.,  3.,  9.,  7.,  5.],
       [ 3., 10.,  3.,  9.,  3.,  5.],
       [ 0.,  2.,  5.,  9.,  7.,  2.],
       [ 0.,  1.,  2.,  3.,  9.,  2.]])

In [9]:
did_rate

array([[1, 1, 1, 1, 0, 1],
       [0, 1, 1, 1, 1, 1],
       [0, 1, 1, 1, 1, 0],
       [0, 1, 1, 1, 1, 1],
       [1, 1, 0, 1, 1, 0],
       [0, 1, 1, 1, 1, 1],
       [0, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [0, 1, 1, 1, 1, 1],
       [0, 1, 1, 1, 1, 1]])

In [24]:
def normalize_ratings(ratings,did_rate):
    num_movies = ratings.shape[0]
    
    ratings_mean = zeros(shape=(num_movies,1))
    ratings_norm = zeros(shape = ratings.shape)
    for i in range(num_movies):
        #get all indexes where there is 1
        idx = where(did_rate[i] ==1)[0]
        
        ratings_mean[i] = mean(ratings[i, idx])
        ratings_norm[i, idx] = ratings[i, idx] - ratings_mean[i]
    return ratings_norm,ratings_mean

    

In [25]:
ratings, ratings_mean = normalize_ratings(ratings, did_rate)


In [26]:
ratings

array([[ 1.  , -2.  ,  0.  ,  0.  ,  0.  ,  1.  ],
       [ 0.  ,  2.2 , -0.8 , -1.8 , -0.8 ,  1.2 ],
       [ 0.  , -1.75, -0.75,  1.25,  1.25,  0.  ],
       [ 0.  ,  3.4 , -4.6 ,  3.4 , -4.6 ,  2.4 ],
       [ 1.25, -1.75,  0.  ,  2.25, -1.75,  0.  ],
       [ 0.  , -1.  ,  2.  ,  0.  ,  3.  , -4.  ],
       [ 0.  ,  0.8 , -3.2 ,  2.8 ,  0.8 , -1.2 ],
       [-2.5 ,  4.5 , -2.5 ,  3.5 , -2.5 , -0.5 ],
       [ 0.  , -3.  ,  0.  ,  4.  ,  2.  , -3.  ],
       [ 0.  , -2.4 , -1.4 , -0.4 ,  5.6 , -1.4 ]])

In [28]:
ratings_mean

array([[7.  ],
       [6.8 ],
       [6.75],
       [5.6 ],
       [5.75],
       [6.  ],
       [6.2 ],
       [5.5 ],
       [5.  ],
       [3.4 ]])

In [35]:
#update some of the key values now
num_users = ratings.shape[1]
num_features = 3
#Initialize Parameters theta(user_prefs), X(movie_features)
movie_features = random.randn(num_movies,num_features)
user_prefs = random.randn(num_users,num_features)
initial_X_and_theta = r_[movie_features.T.flatten(),user_prefs.T.flatten()]

In [37]:
movie_features

array([[ 0.00914085, -0.54152747,  0.71692849],
       [-0.3974475 , -0.11126951, -1.535438  ],
       [-0.15623124, -1.76934064,  0.26553521],
       [ 0.14553896, -1.49306509,  0.08648407],
       [ 0.48320006, -0.38268656, -0.77287369],
       [ 0.39616522, -2.09090186,  0.47876747],
       [ 0.33080227, -0.47333973,  0.54701911],
       [ 0.5958264 , -1.02750719,  2.1639945 ],
       [-1.33214274,  0.6643108 , -1.5392476 ],
       [-0.61630067, -1.4351662 , -1.33419568]])

In [38]:
user_prefs

array([[-0.71126253,  1.88762456, -1.83197711],
       [-0.41813297,  0.84591325,  0.08795583],
       [ 2.28189498, -1.0168791 , -0.67394716],
       [-1.49839322,  0.78138165,  0.39825468],
       [ 0.39457415, -0.49690944, -1.33706892],
       [-0.41927618,  0.92779668,  0.17928958]])

In [40]:
initial_X_and_theta.shape

(48,)

In [39]:
movie_features.T.flatten()

array([ 0.00914085, -0.3974475 , -0.15623124,  0.14553896,  0.48320006,
        0.39616522,  0.33080227,  0.5958264 , -1.33214274, -0.61630067,
       -0.54152747, -0.11126951, -1.76934064, -1.49306509, -0.38268656,
       -2.09090186, -0.47333973, -1.02750719,  0.6643108 , -1.4351662 ,
        0.71692849, -1.535438  ,  0.26553521,  0.08648407, -0.77287369,
        0.47876747,  0.54701911,  2.1639945 , -1.5392476 , -1.33419568])

In [41]:
def unroll_params(X_and_theta, num_users, num_movies, num_features):
	# Retrieve the X and theta matrixes from X_and_theta, based on their dimensions (num_features, num_movies, num_movies)
	# --------------------------------------------------------------------------------------------------------------
	# Get the first 30 (10 * 3) rows in the 48 X 1 column vector
	first_30 = X_and_theta[:num_movies * num_features]
	# Reshape this column vector into a 10 X 3 matrix
	X = first_30.reshape((num_features, num_movies)).transpose()
	# Get the rest of the 18 the numbers, after the first 30
	last_18 = X_and_theta[num_movies * num_features:]
	# Reshape this column vector into a 6 X 3 matrix
	theta = last_18.reshape(num_features, num_users ).transpose()
	return X, theta

In [42]:
temp = initial_X_and_theta
first_30 = temp[:num_movies * num_features]

In [43]:
first_30

array([ 0.00914085, -0.3974475 , -0.15623124,  0.14553896,  0.48320006,
        0.39616522,  0.33080227,  0.5958264 , -1.33214274, -0.61630067,
       -0.54152747, -0.11126951, -1.76934064, -1.49306509, -0.38268656,
       -2.09090186, -0.47333973, -1.02750719,  0.6643108 , -1.4351662 ,
        0.71692849, -1.535438  ,  0.26553521,  0.08648407, -0.77287369,
        0.47876747,  0.54701911,  2.1639945 , -1.5392476 , -1.33419568])

In [46]:
first_30.reshape((num_features, num_movies)).transpose()

array([[ 0.00914085, -0.54152747,  0.71692849],
       [-0.3974475 , -0.11126951, -1.535438  ],
       [-0.15623124, -1.76934064,  0.26553521],
       [ 0.14553896, -1.49306509,  0.08648407],
       [ 0.48320006, -0.38268656, -0.77287369],
       [ 0.39616522, -2.09090186,  0.47876747],
       [ 0.33080227, -0.47333973,  0.54701911],
       [ 0.5958264 , -1.02750719,  2.1639945 ],
       [-1.33214274,  0.6643108 , -1.5392476 ],
       [-0.61630067, -1.4351662 , -1.33419568]])