In [12]:
from numpy import *
num_movies = 10
num_users = 5
ratings = random.randint(11, size = (num_movies, num_users))
print(ratings)

[[ 8  7  9  0  7]
 [ 9  2  8  8  0]
 [ 8  0  0  0  7]
 [ 0  4  5  8  9]
 [10  6  9  6  7]
 [ 7 10  9 10  0]
 [ 7  9  1  6  1]
 [ 7  2  7  8  5]
 [ 9  8  0 10  5]
 [10  0  5  0  1]]


In [13]:
did_rate = (ratings != 0) * 1

In [14]:
ratings.shape

(10, 5)

In [15]:
nikhil_ratings=zeros((num_movies, 1))

In [16]:
nikhil_ratings[0] = 8
nikhil_ratings[4] = 7
nikhil_ratings[7] = 3


In [17]:
print(nikhil_ratings)

[[8.]
 [0.]
 [0.]
 [0.]
 [7.]
 [0.]
 [0.]
 [3.]
 [0.]
 [0.]]


In [18]:
ratings = append(nikhil_ratings,ratings,axis=1)
did_rate = append((nikhil_ratings != 0) * 1,did_rate,axis=1)

In [19]:
ratings

array([[ 8.,  8.,  7.,  9.,  0.,  7.],
       [ 0.,  9.,  2.,  8.,  8.,  0.],
       [ 0.,  8.,  0.,  0.,  0.,  7.],
       [ 0.,  0.,  4.,  5.,  8.,  9.],
       [ 7., 10.,  6.,  9.,  6.,  7.],
       [ 0.,  7., 10.,  9., 10.,  0.],
       [ 0.,  7.,  9.,  1.,  6.,  1.],
       [ 3.,  7.,  2.,  7.,  8.,  5.],
       [ 0.,  9.,  8.,  0., 10.,  5.],
       [ 0., 10.,  0.,  5.,  0.,  1.]])

In [20]:
did_rate

array([[1, 1, 1, 1, 0, 1],
       [0, 1, 1, 1, 1, 0],
       [0, 1, 0, 0, 0, 1],
       [0, 0, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [0, 1, 1, 1, 1, 0],
       [0, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [0, 1, 1, 0, 1, 1],
       [0, 1, 0, 1, 0, 1]])

In [21]:
def normalize_ratings(ratings,did_rate):
    num_movies = ratings.shape[0]
    
    ratings_mean = zeros(shape=(num_movies,1))
    